name: abox-project-workflow

on:

    push:
        branches: main

jobs:

    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build container image and push to ECR
              run: docker build -t public.ecr.aws/t4u4m2y7/abox-project:${{ github.sha }} . && docker push public.ecr.aws/t4u4m2y7/abox-project:${{ github.sha }}

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: setup terraform cli
              uses: hashicorp/setup-terraform@v3

            - name: run terraform script
              run: terraform init && terraform apply && terraform output commit-ref
              env:
                TF_VAR_commit-ref: ${{ github.sha}}
