name: abox-project-workflow

on:

    push:
        branches: main

jobs:

    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4.0.2
              with:
                aws-region: us-east-1
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            - name: login to ECR Repo
              run: aws ecr get-login-password | docker login --username ${{ secrets.ECR_REPO_USERNAME }} --password-stdin ${{ secrets.ECR_REPO_URI }}

            - name: Build container image and push to ECR
              run: docker build -t ${{ secrets.ECR_REPO_URI }}/abox-project:${{ github.sha }} . && docker push ${{ secrets.ECR_REPO_URI }}/abox-project:${{ github.sha }}

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4.0.2
              with:
                aws-region: us-east-1
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  

            - name: setup terraform cli
              uses: hashicorp/setup-terraform@v3

            - name: run terraform script
              run: terraform init && terraform apply --auto-approve && terraform output ip-addr && terraform output commit-ref
              env:
                TF_VAR_commit-ref: ${{ github.sha}}
                TF_VAR_ecr-repo-uri: "${{ secrets.ECR_REPO_URI }}/abox-project"
