name: abox-project-workflow

on:

    push:
        branches: main

jobs:

    build:
        runs-on: debian-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/abox-project:latest

    deploy:
        runs-on: debian-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: setup terraform cli
              uses: hashicorp/setup-terraform@v3